### ISSUE TITLE
Nullish coalescing operator (??)

### ISSUE THREAD

**Issue by mrleblanc101** [hedefalk/atom-vue#111] opened 2020-10-09 19:43 UTC
Syntax highlight breaks when using `??` operator.

<img width="706" alt="Capture d’écran, le 2020-10-09 à 15 43 01" src="https://user-images.githubusercontent.com/17392251/95625208-2209fb00-0a46-11eb-94d1-50d2bcf1a86b.png">

**Comment by mrleblanc101** [comment] 2020-10-09 19:44
Wrong repo

**Comment by mrleblanc101** [comment] 2020-10-09 19:45
Wait nvm, it's the good repo. The extension is called `language-vue` but the repo `atom-vue` which confused me

**Comment by mrleblanc101** [comment] 2021-01-20 23:01
Optional chaining doesn't work either

**Comment by djcaesar9114** [comment] 2021-06-07 11:49
> Optional chaining doesn't work either

I confirm. Is this repo still maintained?

**Comment by hedefalk** [comment] 2021-06-07 11:59
> > Optional chaining doesn't work either
> 
> I confirm. Is this repo still maintained?

Not by me. I gave admin rights to @aidistan who have been maintaining for quite some time (thanks for that!)

Dunno about current status, haven't seen much activity lately…

I wouldn't wanna be any kind of blocker so if someone is invested, I'll hand the torch. Probably better with more active maintainers too…

**Comment by mmccartn** [comment] 2021-11-17 23:15
This issue is caused by [language-javascript](https://github.com/atom/language-javascript) and is *not* related to `language-vue`. I recommend closing this issue and directing users to the open [language-js Pull Request](https://github.com/hedefalk/atom-vue/issues/111) that aims to resolve this (and related) issues with modern js `?`-based operators.

If you don't use the tree-sitter parser, then you can apply the changes from the PR with the following commands:
```bash
git clone https://github.com/icecream17/language-javascript.git
cd ./language-javascript
git checkout operators
rm ./grammars/tree-sitter*
npm install # ignore node-gyp errors
```

**Comment by BrandonDusseau** [comment] 2022-02-10 02:25
For anyone who stumbles across this from Google like I did, the known workaround is to install `language-babel`. This seems to fix syntax highlighting with optional chaining, at least. See [atom/language-javascript#640 comment](https://github.com/atom/language-javascript/issues/640#issuecomment-742677337)

Edit: this solves it for the script portion of a single-file component, but doesn't seem to fix it for use within a template. I'll probably work around this by using computed values instead of using optional chaining within props.

**Comment by djcaesar9114** [comment] 2022-03-19 10:13
> For anyone who stumbles across this from Google like I did, the known workaround is to install `language-babel`. 

Sorry, but it didn't work for me...

**Closed as completed** 2023-01-13 18:49 UTC
