### ISSUE TITLE
Wrong highlighting in block comments

### ISSUE THREAD

**Issue by TheDutchCoder** [hedefalk/atom-vue#34] opened 2016-08-23 13:00 UTC
Hi, there's some odd highlighting in block comments:

![image](https://cloud.githubusercontent.com/assets/1668207/17892551/e0b4bac2-690f-11e6-9c4b-e97656681ee1.png)

Possibly because it thinks the 3rd word is the variable name, but that's not always the case when block commenting on non-methods.

The following example works, because it has a variable name:
![image](https://cloud.githubusercontent.com/assets/1668207/17892586/171d8954-6910-11e6-888b-0c949d0cbbdf.png)

**Comment by aidistan** [comment] 2016-08-23 15:30
Cannot reproduce this issue. More info needed.

![selection_001](https://cloud.githubusercontent.com/assets/3037661/17898208/83b997cc-691c-11e6-83aa-2edf7c09269e.png)

**Comment by TheDutchCoder** [comment] 2016-08-23 15:53
This is literally the only package I installed in Atom, so I can't really help any further.

UI Theme: One Dark
Syntax Theme: One Dark

Maybe I need an additional syntax highlighter for it to work properly?

**Comment by aidistan** [comment] 2016-08-23 16:30
@TheDutchCoder Highlighting of the script section are always handled by the built-in package `language-javascript`, which means no additional package is needed. What's the version of Atom you are using?

**Comment by aidistan** [comment] 2016-08-23 16:40
@TheDutchCoder As I expected, it's related to the lastest version of `language-javascript` and has already been fixed by atom/language-javascript#411.

**Closed as completed by aidistan** 2016-08-23 16:40 UTC
Labels: question

**Comment by TheDutchCoder** [comment] 2016-08-23 17:03
Ah okay, I went ahead and commented on that issue because obviously it doesn't work (yet).

**Comment by aidistan** [comment] 2016-08-23 17:04
That PR was just merged 15 hours ago and has not been published yet :cold_sweat:

**Comment by TheDutchCoder** [comment] 2016-08-23 17:09
Ah, I assumed merging into master would mean it was published already.
