### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by knuks** [hedefalk/atom-vue#55] opened 2017-02-09 10:47 UTC
it will show error 
Installing “hedefalk/atom-vue” failed
       Cannot read property 'getReferenceTarget' of null

**Comment by aidistan** [comment] 2017-02-14 04:47
@knuks can not reproduce this issue on Windows and Linux. Could you provide more infos?

**Comment by aidistan** [comment] 2017-03-21 06:00
Close this issue due to no responce.

**Closed as completed by aidistan** 2017-03-21 06:00 UTC
Labels: invalid
