### ISSUE TITLE
Autocomplete of Sass is broken

### ISSUE THREAD

**Issue by resse92** [hedefalk/atom-vue#46] opened 2016-11-29 02:25 UTC
I just use `l<style lang="sass">`, there is no hint about property hint?
![image](https://cloud.githubusercontent.com/assets/14215749/20694132/02cc96ba-b61e-11e6-8e27-9f5be121e0df.png)

**Comment by aidistan** [comment] 2016-11-29 07:44
The issue has no relation to `atom-vue` and `atom-vue` does not provide any hint function.

It seems like that the SASS atom package you used could not handle the situation well.

**Comment by tuurbo** [comment] 2017-02-26 07:43
@zhuruliang Did you ever find an alternative way to get property hints?

**Comment by inssitu** [comment] 2017-03-15 18:00
Hi @aidistan  you know any solution for this?

**Comment by aidistan** [comment] 2017-03-16 13:26
Hi @inssitu. This issue is caused by the official package `autocomplete-css` which fails to recognize the SASS scope (named `source.sass.embedded.html`) in Vue.

Related lines are: 
- https://github.com/atom/autocomplete-css/blob/master/lib/provider.coffee#L29
- https://github.com/atom/autocomplete-css/blob/master/lib/provider.coffee#L299-L300

If you want this feature badly, you could hack `atom-vue` by changing [this line](https://github.com/hedefalk/atom-vue/blob/266400c54003d780c7ef859cccf67a64d0644b7f/grammars/vue.cson#L174) to `name: "source.sass"`. Though it's not recommended to do this, since it violates the scope naming convention.

This is as far as I could help. I write SCSS more often actually. Good luck!

**Comment by aidistan** [comment] 2017-06-01 13:08
I will keep this issue open and update it according to the progress in atom/autocomplete-css#98

**Comment by aidistan** [comment] 2017-06-03 02:28
My PR atom/autocomplete-css#99 has been merged. Since that's a core package, let's wait the next release version of Atom to fix this.

**Comment by corysimmons** [comment] 2017-07-20 01:01
@aidistan Any update on this? Seems like https://github.com/atom/atom/releases/tag/v1.18.0 hit on June 15.

Would looooveee some autocomplete (and maybe even Emmet?) on `<style lang="scss">` 😍

**Comment by aidistan** [comment] 2017-07-20 06:37
@corysimmons It seems like Atom v1.180 was still packed with `autocomplete-css` v0.16.2 which does not include my PR.

I would love any autocomplete, but maybe it's more suitable to put them in the `language-scss` package?

**Comment by corysimmons** [comment] 2017-07-20 07:08
🤷‍♂️

**Comment by kingsleydon** [comment] 2017-08-09 13:14
Atom 1.19.0 release was still packed with `autocomplete-css` v0.16.2.😓
I try using `apm install https://github.com/atom/autocomplete-css.git` to install the latest version (now v0.17.2) from git repo and now autocomplete on `<style lang="sass">` works well!
![screen shot 2017-08-09 at 20 52 01](https://user-images.githubusercontent.com/10992364/29122822-30d95b48-7d46-11e7-9193-fd7d1abff772.png)
![screen shot 2017-08-09 at 20 52 55](https://user-images.githubusercontent.com/10992364/29122823-31f33db4-7d46-11e7-9c87-7b889fc5cff8.png)

**Comment by aidistan** [comment] 2017-08-09 13:42
@Kingsley-Don Coooool! I have found that Atom v.1.20.0-beta0 is packed with `autocomplete-css` v0.17.2. Let's wait the official release~

**Comment by aidistan** [comment] 2017-12-07 08:21
Already published in v1.20.0

**Closed as completed by aidistan** 2017-12-07 08:21 UTC
Labels: 3rd-party-issue
