### ISSUE TITLE
Autocomplete of Sass is broken in .vue files

### ISSUE THREAD

**Issue by kodekrendel** [hedefalk/atom-vue#66] opened 2017-05-30 14:29 UTC
Hi. When I set `<style lang="sass">` then Atoms stop autocomplete CSS properties (like, color, padding etc). Everything working in .sass files, the issue is only in .vue files.

I read this, and tried to add this to local project, but it doesn't work (and why should it, since I need it only in Atom? don't understant how it's related to webpack anyway)

```
vue: {
  loaders: {
    sass: 'style!css!sass?indentedSyntax',
    scss: 'style!css!sass'
  }
}
```

So, I basically can't use Sass in Vue files, which is frustrating.

**Comment by islas27** [comment] 2017-05-31 05:18
I have the same problem, searched about it and only stuff about Webpack came out, seeing as you had added support por sugarcss in the most recent version then this might be something to solve here?

**Comment by aidistan** [comment] 2017-06-01 07:41
Duplicated with #46 caused by the same reason. I'll reopen #46 and close this one.

Any advice or solution is welcomed to be left there.

**Closed by aidistan** 2017-06-01 07:41 UTC
