### ISSUE TITLE
HTML attribute syntax highlighing in Vue Component Files

### ISSUE THREAD

**Issue by superjoefly** [hedefalk/atom-vue#71] opened 2017-06-22 12:31 UTC
The HTML attributes in .vue component files are not highlighted which makes them difficult to read.
Are there any plans to add this feature to this package?
Thanks :-)

**Comment by aidistan** [comment] 2017-06-26 06:15
@superjoefly 

What do you mean by mentioning "not highlighted"?

![screenshot from 2017-06-26 14-10-22](https://user-images.githubusercontent.com/3037661/27526642-e127ab1a-5a0c-11e7-9b56-0a0f6eb2bcfd.png)

**Comment by DanielMuller** [comment] 2017-07-13 16:10
Duplicate of #57 ?

**Closed as completed** 2017-07-14 03:00 UTC
Labels: duplicate
