### ISSUE TITLE
Wrong colors when adding a question mark before a dot

### ISSUE THREAD

**Issue by djcaesar9114** [hedefalk/atom-vue#114] opened 2021-06-07 10:51 UTC
Hello,
I have a `.vue` file with this:

`<td :rowspan="diplome.scolarites?.length || 1">`

If I don't put the question mark before the point everything is fine, but when I put it, here is what I have (the colors are messed up):

![image](https://user-images.githubusercontent.com/19804251/121004475-069aef80-c78f-11eb-9d48-1fe2cbf90837.png)

**Comment by mmccartn** [comment] 2021-11-17 23:16
Duplicate, please see: https://github.com/hedefalk/atom-vue/issues/111#issuecomment-972252056

**Comment by confused-Techie** [comment] 2023-08-02 23:42
Thanks a ton for reporting this issue!

But this is a duplicate of #109 which is now resolved via updating the TextMate JavaScript Grammar in Pulsar.

So just ensure you are up to date there and this should be resolved.

**Closed as completed by confused-Techie** 2023-08-02 23:42 UTC
